apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  namespace: app-juiceshop-web-dev
  name: app-juiceshop-web-dev-gateway
spec:
  selector:
    istio: ingress-gateway-01
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: app-juiceshop-web-dev
  name: app-juiceshop-web-dev-virtualservice
spec:
  hosts:
  - "*"
  gateways:
  - app-juiceshop-web-dev-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: app-juiceshop-web-dev-service
        port:
          number: 80
